Fix group creation issue
cloudposse/terraform-aws-ses pull request #66
Opened 2023-01-04 16:02 UTC by ncjmlnchth

## what
* We are trying to create a new ses group by setting "ses_user_enabled" to false and "ses_group_enabled" to true in our "ses" module. However, we get this error when applying the changes: 

`│ Error: "policy" contains an invalid JSON policy
│ 
│   with module.ses.aws_iam_group_policy.ses_group_policy[0],
│   on .terraform/modules/ses/main.tf line 70, in resource "aws_iam_group_policy" "ses_group_policy":
│   70:   policy = join("", data.aws_iam_policy_document.ses_policy.*.json)`

* It refers to data.aws_iam_policy_document:

`data "aws_iam_policy_document" "ses_policy" {
  count = (module.this.enabled && var.ses_user_enabled) ? 1 : 0
                                                                                                          
  statement {                                                                                             
    actions   = var.iam_permissions                                                                       
    resources = concat(aws_ses_domain_identity.ses_domain.*.arn, var.iam_allowed_resources)               
  }                                                                                                       
} `

* The count is there to enable or disable this policy document but it only enables it if "var.ses_user_enabled" is true (we want it "false" to create only the ses group). As a workaround, we replaced the "count" line with this:

`count = (module.this.enabled && (var.ses_user_enabled || local.create_group_enabled)) ? 1 : 0`

## why
* Enable group creation without the requirement of setting "ses_user_enabled" to true.

## references
* Closes #65

2023-01-10 17:12 UTC, stephan242 commented
@max-lobur sorry for nagging, but any chance you could have a quick look? Just a one line change.

2023-02-23 11:24 UTC, goruha requested changes

2023-02-23 11:24 UTC, goruha commented on main.tf
> +  count = (module.this.enabled && (var.ses_user_enabled || local.create_group_enabled)) ? 1 : 0
```suggestion
  count = local.create_user_enabled || local.create_group_enabled ? 1 : 0
```

2023-02-23 11:24 UTC, goruha commented on main.tf
> +  count = (module.this.enabled && (var.ses_user_enabled || local.create_group_enabled)) ? 1 : 0
@stephan242 can we improve the condition this way?

2023-02-23 11:25 UTC, goruha commented
/test all

2023-03-03 06:02 UTC, ncjmlnchth commented
@goruha PR's been update with your suggestion.

2023-03-13 13:22 UTC, goruha approved these changes

2023-03-13 13:22 UTC, goruha commented
@ncjmlnchth LGTM
Thanks for your contribution.

2023-03-13 13:22 UTC, merged