Add toggle for custom_from_subdomain DNS record creation
cloudposse/terraform-aws-ses pull request #99
Opened 2024-10-11 14:55 UTC by sarkis

## what

This module currently has no way to disable the custom_from_domain Route53 records from being created. Add a new variable `create_custom_from_subdomain_record` and default it to `true` to preserve the current behavior. Allows users that need this feature to toggle the option to false and get the desired results.

## why

This is a problem for organizations that will need to manage DNS records outside of Route53 or in a different AWS account. Currently, other records in the module have a toggle, but the one for `custom_from_subdomain` seems to have been missed.

## references

closes #98

2024-10-11 20:29 UTC, osterman commented on variables.tf
> +  description = "If provided the module will create a Route53 DNS record for the `From` address subdomain."
```suggestion
  description = "If enabled the module will create a Route53 DNS record for the `From` address subdomain."
```

2024-10-30 18:11 UTC, osterman commented
I'm checking with the team

2024-10-30 18:14 UTC, Benbentwo commented
/terratest

2024-10-30 18:15 UTC, Benbentwo requested changes
Looks like missed `var.`

2024-10-30 18:15 UTC, Benbentwo commented on main.tf
> +  count = local.custom_from_subdomain_enabled && custom_from_dns_record_enabled ? 1 : 0
```suggestion
  count = local.custom_from_subdomain_enabled && var.custom_from_dns_record_enabled ? 1 : 0
```

2024-10-30 18:16 UTC, Benbentwo commented
/terratest

2024-10-30 18:19 UTC, Benbentwo approved these changes

2024-10-30 20:37 UTC, Benbentwo commented
/terratest

2024-10-30 20:44 UTC, Benbentwo approved these changes

2024-10-30 21:01 UTC, osterman approved these changes

2024-10-30 21:01 UTC, merged